"""empty message

Revision ID: b3e4579e9cb7
Revises: 
Create Date: 2024-11-05 12:03:22.871624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e4579e9cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('contraseña', sa.String(length=128), nullable=True),
    sa.Column('conf_contraseña', sa.String(length=128), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.Column('descripcion', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('direccion', sa.String(length=128), nullable=True),
    sa.Column('telefono', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.Column('tipo_documento', sa.String(length=128), nullable=True),
    sa.Column('numero_documento', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('conf_email', sa.String(length=128), nullable=True),
    sa.Column('direccion', sa.String(length=128), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.String(length=128), nullable=True),
    sa.Column('rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Integer(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('inventario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=128), nullable=True),
    sa.Column('inventario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=128), nullable=True),
    sa.Column('factura', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['factura'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=128), nullable=True),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=True),
    sa.Column('stock_min', sa.Integer(), nullable=True),
    sa.Column('stock_max', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=128), nullable=True),
    sa.Column('proveedor', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=True),
    sa.Column('inventario', sa.Integer(), nullable=True),
    sa.Column('venta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['inventario'], ['inventario.id'], ),
    sa.ForeignKeyConstraint(['proveedor'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['venta'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('venta')
    op.drop_table('tipo_movimiento')
    op.drop_table('factura')
    op.drop_table('empleado')
    op.drop_table('rol')
    op.drop_table('proveedor')
    op.drop_table('inventario')
    op.drop_table('categoria')
    op.drop_table('administrador')
    # ### end Alembic commands ###
